languages:
    Ruby: true
    JavaScript: true

engines:
  brakeman:
    enabled: false
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  watson:
    enabled: false
  rubymotion:
    enabled: false
  foodcritic:
    enabled: false

Metrics/LineLength:
  Max: 100

ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - Gemfile.lock

exclude_paths:
- config/**/*
- db/**/*
- db_dashboard/**/*
- script/**/*
- spec/**/*
- test/**/*
- vendor/**/*
